### PR TITLE
Cookie secret to ENV var

### PR DESCRIPTION
**Pull request by Webunity**
Moved cookie secret to env var

### CODE REVIEW

**Comment by hardillb** [comment]
Thanks,

In future it is useful to explain why you want to make changes when you submit pull request, then the reviewer has some context. In this case I'm assuming it's a security precaution against people trying to spoof session cookies.

Can I also ask what you are planning to do with this code? I will be submitting it for public listing with Google in the next week when I get back home so it will be available to all. It was not really intended for people to run their own instances.

**Comment by Webunity** [comment]
> In future it is useful to explain why you want to make changes when you submit pull request, then the reviewer has some context. In this case I'm assuming it's a security precaution against people trying to spoof session cookies.
>

Point taken; i just saw the todo and wanted to help you a bit.

> Can I also ask what you are planning to do with this code? I will be submitting it for public listing with Google in the next week when I get back home so it will be available to all. It was not really intended for people to run their own instances.

Sure you can :) I have my own server running at home with traefik, conbee II, zwave etc. and i would like to be as less dependent on external services as possible. I also like to understand the stuff i am running therefore digging through the written code. I am now in the process of seeing if i can get your code to boot up locally without any provided documentation. Since i also saw you where providing the initial bits of local control, i was just curious if you would have a good alternative to gBridge. I do hope you plan on keeping this repo alive and up to date, and i will make sure to contribute wherever i can.

**Comment by Webunity** [comment]
btw, there is an error in your package.json author email address of the localcontrol package i think.

**Comment by hardillb** [comment]
OK thanks. The lack of setup docs are sort of on purpose, if you can't work it out you probably shouldn't be trying to run an instance... and I think it's better to have one public instance to stop things fracturing off in too many different directions. I can understand why some people might want to run their own, but once you've signed up to Google/Amazon you really can't wave the privacy flag anymore.

The intention is to keep it going, but I may not publish the local control stuff to start with as it is still in Developer Beta with Google (they made big changes just before Christmas to the API) so I may wait till it stabilises. Announcements will be made in the #google-home-assistant slack channel

**Comment by Webunity** [comment]
> OK thanks. The lack of setup docs are sort of on purpose, if you can't work it out you probably shouldn't be trying to run an instance... and I think it's better to have one public instance to stop things fracturing off in too many different directions. 
> 

Mainly for latency reasons if any (and learning). Let's see how far i get and i'll make sure to CC you my docker files if i'm successful so you can decide if and how you publish them.

> The intention is to keep it going, but I may not publish the local control stuff to start with as it is still in Developer Beta with Google (they made big changes just before Christmas to the API) so I may wait till it stabilises.
>
Yeah i saw the youtube video, i have been waiting for local control since ages. (I'm running some arduino based thingies)

> Announcements will be made in the #google-home-assistant slack channel
>
Which 'server' for slack? I am on discuss but not on the node-red slack channel if there is any. 

Anyway; after your answer enough slowchat in this pull request.I'll move my questions and answers to slack :)

For now; happy new year and thank you for all your work.

**Comment by hardillb** [comment]
There is a link on the bottom of the Node-RED homepage that will send you a slack invite.

Local control should fix the latency.

**Pull request merged**
