### PR TITLE
Update device.js

### PR DESCRIPTION
**Pull request by Webunity**
Fixes auto-increment issue in case you are adding new devices but haven't set the 'id' (default if you add a new device via the UI)

### CODE REVIEW

**Comment by hardillb** [comment]
This can not be changed, it needs to return a string not a number for the output to match the Google Schema when they look up the devices.

**Comment by Webunity** [comment]
I am not sure about that tbh; Google _did_ discover the devices correctly with this fix in and a switch command for example is working correctly. What should i test to see if this can be merged or not?

**Comment by hardillb** [comment]
You can give a FULL description of what failed, adding new devices via the UI works perfectly fine with the original code.

**Comment by Webunity** [comment]
On the UI i get this:
image

And a stacktrace shows it fails at the `return value.toString();` part of the schema.

**Comment by hardillb** [comment]
I need to see the whole stacktrace

**Comment by Webunity** [comment]
I have been trying to get the stacktrace but it only showed up when i created an empty javascript file; with the mongoose connection at the top, included the model and tried to add a new device via that way. Otherwise it all ends up in the 404 handler (e.g. a try-catch around the device.save() call in "PUT /user/devices" also doesn't give back any information) All i know for sure is that without the pull request it fails, and with it seems to work. Maybe different mongodb version?

**Comment by hardillb** [comment]
Since it's working just fine for me, I'm not really that interested in tracking this down and I'm not going to merge this one.

**Pull request closed without merging**
